# Generated by Django 5.2.3 on 2025-06-18 14:46

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_course_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='days',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Mon', 'Monday'), ('Tue', 'Tuesday'), ('Wed', 'Wednesday'), ('Thu', 'Thursday'), ('Fri', 'Friday'), ('Sat', 'Saturday'), ('Sun', 'Sunday')], max_length=27),
        ),
    ]
